# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sys_master_pb2 as sys__master__pb2


class SysMasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateLobby = channel.unary_unary(
                '/master.SysMasterService/UpdateLobby',
                request_serializer=sys__master__pb2.NewLobbyInfo.SerializeToString,
                response_deserializer=sys__master__pb2.Status.FromString,
                )


class SysMasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateLobby(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SysMasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateLobby': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLobby,
                    request_deserializer=sys__master__pb2.NewLobbyInfo.FromString,
                    response_serializer=sys__master__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'master.SysMasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SysMasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateLobby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/master.SysMasterService/UpdateLobby',
            sys__master__pb2.NewLobbyInfo.SerializeToString,
            sys__master__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
