# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sys_worker_pb2 as sys__worker__pb2


class SysWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewLobby = channel.unary_unary(
                '/worker.SysWorkerService/NewLobby',
                request_serializer=sys__worker__pb2.LobbyParams.SerializeToString,
                response_deserializer=sys__worker__pb2.MasterStatus.FromString,
                )
        self.MasterJoinLobby = channel.unary_unary(
                '/worker.SysWorkerService/MasterJoinLobby',
                request_serializer=sys__worker__pb2.LobbyParams.SerializeToString,
                response_deserializer=sys__worker__pb2.MasterStatus.FromString,
                )
        self.CheckStatus = channel.unary_unary(
                '/worker.SysWorkerService/CheckStatus',
                request_serializer=sys__worker__pb2.Null.SerializeToString,
                response_deserializer=sys__worker__pb2.MasterStatus.FromString,
                )


class SysWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewLobby(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MasterJoinLobby(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SysWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewLobby': grpc.unary_unary_rpc_method_handler(
                    servicer.NewLobby,
                    request_deserializer=sys__worker__pb2.LobbyParams.FromString,
                    response_serializer=sys__worker__pb2.MasterStatus.SerializeToString,
            ),
            'MasterJoinLobby': grpc.unary_unary_rpc_method_handler(
                    servicer.MasterJoinLobby,
                    request_deserializer=sys__worker__pb2.LobbyParams.FromString,
                    response_serializer=sys__worker__pb2.MasterStatus.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=sys__worker__pb2.Null.FromString,
                    response_serializer=sys__worker__pb2.MasterStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.SysWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SysWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewLobby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.SysWorkerService/NewLobby',
            sys__worker__pb2.LobbyParams.SerializeToString,
            sys__worker__pb2.MasterStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MasterJoinLobby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.SysWorkerService/MasterJoinLobby',
            sys__worker__pb2.LobbyParams.SerializeToString,
            sys__worker__pb2.MasterStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.SysWorkerService/CheckStatus',
            sys__worker__pb2.Null.SerializeToString,
            sys__worker__pb2.MasterStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
