# Version of docker-compose
version: '3.8'

# Services
services:
  # Database service
  redis:
    # Image of the container
    image: redis:7.2.4-alpine # Image of redis
    
    # Restart the container always
    restart: always # Restart the container always
    
    # Ports
    ports:
      - '6379:6379'
    
    # Command to run the container
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

    # Environment variables from .env file
    env_file:
      - .env 
    
    # Volumes for persisting data
    volumes: 
      - ./data:/data